[project]
name = "well_aligned_pairs"
description = "A SageMath package for well-aligned pairs"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
]
license = "GPL-2.0-or-later"
keywords = ['sagemath', 'combinatorics']
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'Programming Language :: Python :: 3.7',
    'Topic :: Scientific/Engineering :: Mathematics',
]
authors = [
    {name = "Alexander N. Wilson", email = "math@alexandernwilson.com"},
]
dynamic = ['version']

[project.urls]
Homepage = "https://github.com/wilsoa/well_aligned_pairs"

[tool.setuptools]
packages = [
    'well_aligned_pairs'
]

[tool.setuptools.dynamic]
version = {file = ["VERSION"]}

# For including demos later
# [tool.setuptools.package-data]
# "simple_sagemath_package" = ["demos/*"]  # CURRENTLY BROKEN: the demos files are not shipped in the .tar.gz